let express=require("express")
const { reg, login } = require("../controllers/usercont")
const { addPost, getAll, getByCat, postsByMe, getPosts,addlike, adddlike,approve, rejectPost } = require("../controllers/postcont")
let rt=new express.Router()
rt.post("/reg",reg)
rt.post("/login",login)
rt.post("/add",addPost)
rt.get("/",getAll)
rt.get("/posts",getPosts)
rt.get("/posts/:cat",getByCat)
rt.get("/postsbyme/:uid",postsByMe)
rt.put("/approve",approve)
rt.post("/addlike",addlike)
rt.post("/adddlike",adddlike)
rt.delete("/posts/:id",rejectPost)
module.exports=rt